### ISSUE TITLE
Run Katan in a Docker container

### ISSUE THREAD

**Issue by DevNatan** [KatanPanel/Katan#11]
**Is your feature request related to a problem? Please describe.**
The only current way to successfully run the Katan server is on the local host, with privileges. This is because we have not yet provided a solution to explore the files on the servers without being directly connected to them, outside the Docker environment. 

**Note**: container created by Katan have a common network (`katan0`) that is created the first time that Katan is run, it can serve something.

**Additional context**
To do this you will need to create a new configuration option and a new [`FileSystem`](https://github.com/KatanPanel/Katan/blob/dev/file-system/src/main/kotlin/me/devnatan/katan/fs/FileSystem.kt) implementation and switch it during the initialization of the [file system module](https://github.com/KatanPanel/Katan/tree/dev/file-system).

**Comment by luigieai** [comment]
Why not use docker volumes and mount Host volume to the (Katan) container? Or all containers have a shared volume between them?

**Comment by DevNatan** [comment]
> Why not use docker volumes and mount Host volume to the (Katan) container? Or all containers have a shared volume between them?

This was considered, however, the question is how Katan (inside his container) will access data from the other containers created ince the server container cannot be linked to the host, unlike Katan itself.

**Comment by luigieai** [comment]
Well, you stated that the main issue is navigating to files and doing actions in others containers right? Why you can't do this with ssh?
You can expose the docker socket for the Katan containter too, like following example:
`docker run -v /var/run/docker.sock:/var/run/docker.sock --name containerB myimage ...`
Iff Katan container has any docker client, you will control the others containers from him.

**Comment by DevNatan** [comment]
> Well, you stated that the main issue is navigating to files and doing actions in others containers right? Why you can't do this with ssh?

SSH is a good option, I will start to think about how to create his implementation.
since I marked this issue as a low priority but it is something to have in Katan as soon as possible.

> You can expose the docker socket for the Katan containter too, like following example:
> `docker run -v /var/run/docker.sock:/var/run/docker.sock --name containerB myimage ...`
> Iff Katan container has any docker client, you will control the others containers from him.

yes, I am aware of this, thanks.
